### ISSUE TITLE
will you give an example about cocos creator with Pony lib?

### ISSUE THREAD

**Issue by sonygod** [AxGord/Pony#7]
will you give an example about cocos creator with Pony lib?

typescript 

     const {ccclass, property} = cc._decorator;

    @ccclass
    export class MyModule extends cc.Component {
        @property (cc.String)
        myName: string = "";

        @property (cc.Node)
        myNode: cc.Node = null;
    }

**Comment by AxGord** [comment]
@sonygod https://github.com/AxGord/Pony/wiki/Cocos-Creator

**Comment by sonygod** [comment]
How to define @property as typescript?

**Comment by AxGord** [comment]
@property not implemented
You can pass them through js, or access the necessary nodes from haxe
