### ISSUE TITLE
XMLTools from docs does not go anywhere.

### ISSUE THREAD

**Issue by nanjizal** [AxGord/Pony#8]
XMLTools from docs does not go anywhere.
http://axgord.github.io/Pony/docs/pony/XMLTools.html

I looked in the code base but was unsure where XMLTools was.  

Not yet tried out Pony, but seems interesting project. thumbs up.

**Comment by AxGord** [comment]
https://github.com/AxGord/Pony/blob/haxe3/src/pony/text/XmlTools.hx

I will try to update the documentation as soon as possible.

**Comment by nanjizal** [comment]
No hurry for me, I just was browsing out of curiousity. Library seem to cover lots of things would it be ideal broken into separate modules and users can choose ones that interest them. I know the down side is some find multiple haxelibs scary but then it's much easier to define them in the readme. Separation can force decoupling which can have advantages.

**Comment by AxGord** [comment]
Reference updated http://axgord.github.io/Pony/

Splitting into separate libraries is time-consuming and slows down development. But maybe I will do it in the future.
