### ISSUE TITLE
Uncaught exception calling `pony create heapsxml`

### ISSUE THREAD

**Issue by Christian-Broomfield** [AxGord/Pony#9]
Description:

1. I installed pony via `haxelib install pony` and `haxelib run pony`
2. I created a new, empty folder for the project.
3. In an administrator terminal I called `pony create heapsxml`

Output on the console:
```
.vscode/launch.json saved
.vscode/extensions.json saved
.vscode/tasks.json saved
Save gitignore file
Called from ? line 1
Called from Main.hx line 76
Called from pony/magic/Commander.hx line 17
Called from pony/magic/builder/CommanderBuilder.hx line 89
Called from pony/events/Event2.hx line 69
Called from create/Create.hx line 39
Called from create/Create.hx line 44
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx line 68
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx line 49
Uncaught exception - [file_open,C:\HaxeToolkit\haxe\lib\pony/1,6,1/hxformat.json]
```

VSCode project structure:
![VSCode_Pony](https://user-images.githubusercontent.com/297806/146637949-131e27a4-5f47-4b06-bff6-8683faeea058.PNG)

Version:
![PonyVersion](https://user-images.githubusercontent.com/297806/146637944-0a35ee95-ff4b-4a6b-8f50-56b4bff4aca5.PNG)

I am using Windows 10.

**Comment by AxGord** [comment]
Fixed
Update haxelib v 1.6.4. Added hxformat.json to haxelib
